import React from 'react';
import { AbsoluteFill, interpolate, useCurrentFrame, useVideoConfig, spring } from 'remotion';
import { T } from '../../theme';

// Scene 7 cutaway, craft pass: depth (radial metal gradients, shadows,
// vignette), physical motion (springs, eased camera push), rotor with
// machined-ring texture and hot glow at the pad contact patch. The goal is
// "drawn by someone who cares", not "generated by something that doesn't".
const CX = 960, CY = 560;

export const BrakeCorner = () => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  const spin = frame * 1.1;
  const pop = (delay) => spring({ frame: frame - delay, fps, config: { damping: 14, mass: 0.6 } });
  // slow cinematic push-in over the whole scene
  const push = interpolate(frame, [0, 900], [1, 1.09]);
  const drift = interpolate(frame, [0, 900], [0, -18]);
  const glow = 0.5 + 0.5 * Math.sin(frame / 17);

  const label = (x, y, tx, ty, text, delay) => {
    const s = pop(delay);
    return (
      <g opacity={s}>
        <line x1={x} y1={y} x2={x + (tx - x) * s} y2={y + (ty - y) * s} stroke={T.accent} strokeWidth={3} strokeLinecap="round" />
        <circle cx={x} cy={y} r={7} fill={T.accent} style={{ filter: 'url(#softglow)' }} />
        <g transform={`translate(${tx} ${ty}) scale(${0.9 + 0.1 * s})`}>
          <rect x={tx > CX ? 10 : -230} y={-30} width={220} height={52} rx={26}
            fill="rgba(10,16,22,0.85)" stroke={T.accent} strokeWidth={1.5} />
          <text x={tx > CX ? 120 : -120} y={7} fill={T.text} fontSize={30}
            fontFamily={T.font} fontWeight="bold" textAnchor="middle" letterSpacing={1}>{text}</text>
        </g>
      </g>
    );
  };

  return (
    <AbsoluteFill style={{ background: 'radial-gradient(ellipse at 45% 40%, #24313E 0%, #16202A 55%, #0C141B 100%)' }}>
      <AbsoluteFill style={{ transform: `scale(${push}) translateY(${drift}px)`, justifyContent: 'center', alignItems: 'center' }}>
        <svg width="1920" height="1080">
          <defs>
            <radialGradient id="steel" cx="42%" cy="38%">
              <stop offset="0%" stopColor="#8B9DAB" />
              <stop offset="55%" stopColor="#5A6D7C" />
              <stop offset="100%" stopColor="#394854" />
            </radialGradient>
            <radialGradient id="hubsteel" cx="45%" cy="40%">
              <stop offset="0%" stopColor="#8B9BA8" />
              <stop offset="100%" stopColor="#3E4E5B" />
            </radialGradient>
            <linearGradient id="caliperpaint" x1="0" y1="0" x2="0" y2="1">
              <stop offset="0%" stopColor="#FF9A6B" />
              <stop offset="45%" stopColor="#E8683A" />
              <stop offset="100%" stopColor="#9C3A1D" />
            </linearGradient>
            <filter id="dropsh" x="-30%" y="-30%" width="160%" height="160%">
              <feDropShadow dx="0" dy="14" stdDeviation="18" floodColor="#000" floodOpacity="0.55" />
            </filter>
            <filter id="softglow" x="-80%" y="-80%" width="260%" height="260%">
              <feGaussianBlur stdDeviation="6" result="b" />
              <feMerge><feMergeNode in="b" /><feMergeNode in="SourceGraphic" /></feMerge>
            </filter>
            <radialGradient id="hotspot" cx="50%" cy="50%">
              <stop offset="0%" stopColor="#FF7A45" stopOpacity="0.8" />
              <stop offset="100%" stopColor="#FF7A45" stopOpacity="0" />
            </radialGradient>
          </defs>

          {/* ghosted tire/wheel with soft presence */}
          <circle cx={CX} cy={CY} r={430} fill="none" stroke="#5C6E7C" strokeWidth={26} opacity={0.14} />
          <circle cx={CX} cy={CY} r={430} fill="none" stroke="#8FA1B0" strokeWidth={2} strokeDasharray="3 16" opacity={0.35} />

          {/* rotor: layered steel with machined rings */}
          <g style={{ filter: 'url(#dropsh)' }}>
            <circle cx={CX} cy={CY} r={264} fill="url(#steel)" stroke="#1A242C" strokeWidth={3} />
            {/* machined rings: alternating light/dark for visible texture */}
            {Array.from({ length: 12 }, (_, i) => (
              <circle key={i} cx={CX} cy={CY} r={104 + i * 13} fill="none"
                stroke={i % 2 ? '#2A3944' : '#93A6B3'} strokeWidth={i % 2 ? 2.4 : 1.2} opacity={i % 2 ? 0.85 : 0.3} />
            ))}
            {/* brushed-metal sheen sweeping with the spin — makes rotation legible */}
            <path d={`M ${CX - 250} ${CY - 90} A 264 264 0 0 1 ${CX - 60} ${CY - 257}`}
              stroke="#DCE8F0" strokeWidth={56} fill="none" opacity={0.18} strokeLinecap="round"
              transform={`rotate(${spin * 0.5} ${CX} ${CY})`} />
            {/* cross-drilled holes rotating with the disc — unmistakable spin cue */}
            <g transform={`rotate(${spin} ${CX} ${CY})`}>
              {Array.from({ length: 14 }, (_, i) => {
                const a = (i * (360 / 14)) * Math.PI / 180;
                return <g key={i}>
                  <circle cx={CX + Math.cos(a) * 178} cy={CY + Math.sin(a) * 178} r={7} fill="#141D24" />
                  <circle cx={CX + Math.cos(a + 0.22) * 232} cy={CY + Math.sin(a + 0.22) * 232} r={7} fill="#141D24" />
                </g>;
              })}
            </g>
            {/* hot contact patch under the pads */}
            <circle cx={CX} cy={CY - 232} r={54} fill="url(#hotspot)" opacity={glow * 0.7} />
          </g>

          {/* hub with lugs */}
          <g style={{ filter: 'url(#dropsh)' }}>
            <circle cx={CX} cy={CY} r={84} fill="url(#hubsteel)" stroke="#1A242C" strokeWidth={3} />
            <circle cx={CX} cy={CY} r={30} fill="#232E38" stroke="#111920" strokeWidth={2} />
            {Array.from({ length: 5 }, (_, i) => {
              const a = (i * 72 - 90 + spin) * Math.PI / 180;
              return <g key={i} transform={`translate(${CX + Math.cos(a) * 52} ${CY + Math.sin(a) * 52})`}>
                <circle r={13} fill="#1B2630" />
                <circle r={13} fill="none" stroke="#93A5B2" strokeWidth={2} opacity={0.7} />
                <circle r={5} fill="#93A5B2" opacity={0.5} />
              </g>;
            })}
          </g>

          {/* caliper: painted, dimensional, straddling 12 o'clock */}
          <g style={{ filter: 'url(#dropsh)' }}>
            <path d={`M ${CX - 150} ${CY - 328} A 338 338 0 0 1 ${CX + 150} ${CY - 328} L ${CX + 122} ${CY - 208} A 242 242 0 0 0 ${CX - 122} ${CY - 208} Z`}
              fill="url(#caliperpaint)" stroke="#5E2412" strokeWidth={3} />
            {/* bleeder + bridge details */}
            <circle cx={CX - 92} cy={CY - 296} r={9} fill="#5E2412" />
            <circle cx={CX + 92} cy={CY - 296} r={9} fill="#5E2412" />
            <rect x={CX - 34} y={CY - 344} width={68} height={18} rx={9} fill="#B8471F" stroke="#5E2412" strokeWidth={2} />
            {/* caliper inspection window showing the pad against the disc */}
            <path d={`M ${CX - 58} ${CY - 318} A 330 330 0 0 1 ${CX + 58} ${CY - 318} L ${CX + 50} ${CY - 276} A 288 288 0 0 0 ${CX - 50} ${CY - 276} Z`}
              fill="#26313B" stroke="#5E2412" strokeWidth={3} />
            <path d={`M ${CX - 50} ${CY - 306} A 320 320 0 0 1 ${CX + 50} ${CY - 306} L ${CX + 46} ${CY - 282} A 296 296 0 0 0 ${CX - 46} ${CY - 282} Z`}
              fill="#E3B84A" />
            {/* pad edges emerging under the caliper, thicker so the label has a target */}
            <path d={`M ${CX - 116} ${CY - 250} A 268 268 0 0 1 ${CX + 116} ${CY - 250} L ${CX + 104} ${CY - 212} A 236 236 0 0 0 ${CX - 104} ${CY - 212} Z`}
              fill="#E3B84A" stroke="#7A5F1E" strokeWidth={2.5} />
          </g>

          {/* labels spring in, narration order */}
          {label(CX + 186, CY + 186, CX + 470, CY + 330, 'ROTOR', 20)}
          {label(CX + 10, CY - 336, CX + 430, CY - 430, 'CALIPER', 55)}
          {label(CX - 112, CY - 232, CX - 450, CY - 60, 'BRAKE PADS', 90)}
          {label(CX + 42, CY + 42, CX + 420, CY + 130, 'HUB', 125)}
        </svg>
      </AbsoluteFill>
      {/* vignette + title, outside the camera push so they stay pinned */}
      <AbsoluteFill style={{ background: 'radial-gradient(ellipse at center, transparent 55%, rgba(0,0,0,0.5) 100%)', pointerEvents: 'none' }} />
      <div style={{ position: 'absolute', left: 90, top: 74 }}>
        <div style={{ color: T.text, fontFamily: T.font, fontWeight: 'bold', fontSize: 40 }}>The front corner, opened up</div>
        <div style={{ color: T.dim, fontFamily: T.font, fontSize: 26, marginTop: 6 }}>pads squeeze the spinning rotor — friction slows the wheel</div>
      </div>
    </AbsoluteFill>
  );
};
